export const actions = {
    profile: {
        PROFILE_DATA_FETCHING: "PROFILE_DATA_FETCHING",
        PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
        PROFILE_DATA_FETCHED_ERROR: "PROFILE_DATA_FETCHED_ERROR",
        BIO_UPDATED: "BIO_UPDATED",
        IMAGED_UPDATED: "IMAGE_UPDATED"
    }
}