export const actions = {
    profile: {
        PROFILE_DATA_FETCHING: "PROFILE_DATA_FETCHING",
        PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
        PROFILE_DATA_FETCHED_ERROR: "PROFILE_DATA_FETCHED_ERROR",
        BIO_UPDATED: "BIO_UPDATED",
        IMAGED_UPDATED: "IMAGE_UPDATED",
        POST_DELETE: "POST_DELETE",
        DATA_UPDATED: "DATA_UPDATED"
    },
    post: {
        DATA_FETCHING: "DATA_FETCHING",
        DATA_FETCHED: "DATA_FETCHED",
        DATA_FETCH_ERROR: "DATA_FETCH_ERROR",
        DATA_CREATE: "DATA_CREATE",
        DELETE: "DELETE",
        DATA_UPDATED: "DATA_UPDATED"
    },
}